package weather.serverside.gui;

/**
 * Class displays information on the various server services.  
 * 
 * @author Zach Rothweiler
 * @author Ty Vanderstappen
 * @version Spring 2012
 */
public class ServerHealthWindow extends javax.swing.JFrame {

    /**
     * Creates new form ServerHealthWindow
     */
    public ServerHealthWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsTabs = new javax.swing.JTabbedPane();
        servicesSummaryPanel1 = new weather.serverside.gui.component.ServicesSummaryPanel();
        storageSummaryPanel1 = new weather.serverside.gui.component.StorageSummaryPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Weather Viewer - Administrator Services");

        optionsTabs.addTab("Service Summary", servicesSummaryPanel1);
        optionsTabs.addTab("Storage", storageSummaryPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsTabs, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ServerHealthWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane optionsTabs;
    private weather.serverside.gui.component.ServicesSummaryPanel servicesSummaryPanel1;
    private weather.serverside.gui.component.StorageSummaryPanel storageSummaryPanel1;
    // End of variables declaration//GEN-END:variables
}
