package weather.clientside.gui.client;

import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import weather.ApplicationControlSystem;
import weather.common.gui.component.BUDialog;
import weather.clientside.utilities.BarebonesBrowser;
import weather.common.utilities.PropertyManager;
import weather.common.utilities.WeatherLogger;

/**
 * Displays general information about the software.
 * 
 * @author Software Engineering
 * @author Mike Graboske
 * @author Ty Vanderstappen
 */

public class AboutWindow extends BUDialog {
    private File licenseFile;

    public AboutWindow(ApplicationControlSystem clientControl) {
        super(clientControl);
        this.licenseFile = new File("Documents"+File.separator+"License.doc");
        initComponents();
        noLicenseLabel.setVisible(false);
        populateAuthors();
        populateAttributions();
        OracleLink.setText(PropertyManager.getGUIProperty("oracle"));
        BUWeatherLink.setText(PropertyManager.
                getGUIProperty("weatherAppHomePage"));
        classPictureLabel.setText(PropertyManager.
                getGUIProperty("classPictures"));
        weatherDenLabel.setText(PropertyManager.getGUIProperty("buWeatherDen"));
        super.postInitialize(true);
    }

    /*
     * This populates the Authors JTextPane with all the students from each year.
     */
    private void populateAuthors() {
        Document doc;
        Vector<String> groupNames = new Vector<String>();
        String groups = PropertyManager.getGUIProperty("groups");
        StringTokenizer st = new StringTokenizer(groups, ",", false);
        while (st.hasMoreTokens()) {
            groupNames.add(st.nextToken());
        }
        doc = authorsJTextPane.getDocument();
        SimpleAttributeSet bold = new SimpleAttributeSet();
        SimpleAttributeSet italic = new SimpleAttributeSet();
        SimpleAttributeSet plain = new SimpleAttributeSet();
        StyleConstants.setBold(bold, true);
        StyleConstants.setItalic(italic, true);
        StyleConstants.setBold(plain, false);
        try {
            for (String s : groupNames) {
                doc.insertString(doc.getLength(), s, bold);
                doc.insertString(doc.getLength(), PropertyManager.getGUIProperty(s), plain);
                doc.insertString(doc.getLength(), "\n\n", bold);
            }

        } catch (BadLocationException badLocationException) {
        }
        authorsJTextPane.setDocument(doc);
        // Scroll to the top.
        authorsJTextPane.setCaretPosition(0);
    }

    /**
     * This populates the Attributions JTexpane.
     */
    private void populateAttributions() {
        Document doc = attributionsJTextPane.getDocument();

        SimpleAttributeSet plain = new SimpleAttributeSet();

        Vector<String> attributionsList = new Vector<String>();
        String attributions = PropertyManager.getGUIProperty("attributions");
        StringTokenizer st = new StringTokenizer(attributions, ",", false);
        while (st.hasMoreTokens()) {
            attributionsList.add(st.nextToken());
        }

        try {
            for (String str : attributionsList) {
                doc.insertString(doc.getLength(), PropertyManager.getGUIProperty(str), plain);
            }
        }
        catch (BadLocationException ex) {
        }
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aboutLabel = new javax.swing.JLabel();
        authorsLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        authorsJTextPane = new javax.swing.JTextPane();
        copyrightLabel = new javax.swing.JLabel();
        licenseButton = new javax.swing.JButton();
        attributionPanel = new javax.swing.JPanel();
        attributionsLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        attributionsJTextPane = new javax.swing.JTextPane();
        OracleLink = new javax.swing.JLabel();
        BUWeatherLink = new javax.swing.JLabel();
        classPictureLabel = new javax.swing.JLabel();
        weatherDenLabel = new javax.swing.JLabel();
        noLicenseLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Weather Viewer - About");
        setIconImage(null);
        setIconImages(null);

        aboutLabel.setText(PropertyManager.getGUIProperty("about"));

        authorsLabel.setText("Authors:");

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(51, 153, 0));

        authorsJTextPane.setEditable(false);
        jScrollPane1.setViewportView(authorsJTextPane);

        copyrightLabel.setText("Copyright Bloomsburg University®, All Rights Reserved.");

        licenseButton.setText("BU License");
        licenseButton.setToolTipText("The License of the software");
        licenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseButtonActionPerformed(evt);
            }
        });

        attributionsLabel.setText("Attributions:");

        attributionsJTextPane.setEditable(false);
        jScrollPane2.setViewportView(attributionsJTextPane);

        OracleLink.setForeground(new java.awt.Color(0, 51, 204));
        OracleLink.setToolTipText("The Oracle Corporation Website");
        OracleLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OracleLinkMouseClicked(evt);
            }
        });

        BUWeatherLink.setForeground(new java.awt.Color(0, 51, 204));
        BUWeatherLink.setToolTipText("BU Weather application home page");
        BUWeatherLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BUWeatherLinkMouseClicked(evt);
            }
        });

        classPictureLabel.setToolTipText("Developers' picture");
        classPictureLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classPictureLabelMouseClicked(evt);
            }
        });

        weatherDenLabel.setToolTipText("BU Weather Den Web Site");
        weatherDenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                weatherDenLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout attributionPanelLayout = new javax.swing.GroupLayout(attributionPanel);
        attributionPanel.setLayout(attributionPanelLayout);
        attributionPanelLayout.setHorizontalGroup(
            attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(attributionPanelLayout.createSequentialGroup()
                .addGroup(attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attributionsLabel)
                    .addGroup(attributionPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BUWeatherLink, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OracleLink, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(weatherDenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(classPictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        attributionPanelLayout.setVerticalGroup(
            attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attributionPanelLayout.createSequentialGroup()
                .addComponent(attributionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BUWeatherLink, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                    .addComponent(classPictureLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addGroup(attributionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OracleLink, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weatherDenLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        noLicenseLabel.setForeground(new java.awt.Color(255, 0, 0));
        noLicenseLabel.setText("The license does not exist in your PC.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attributionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorsLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutLabel)
                            .addComponent(copyrightLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(licenseButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(noLicenseLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(copyrightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aboutLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(licenseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(authorsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(noLicenseLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attributionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method will open the sun webSite after the link has been clicked
     * in the about window.
     * @param evt The MouseEvent to see if the Sun Link has been clicked.
     */
    private void OracleLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OracleLinkMouseClicked
        BarebonesBrowser.openURL("http://www.oracle.com/us/technologies/java/index.html",
                this);
}//GEN-LAST:event_OracleLinkMouseClicked

    /**
     * This method will open the BU Weather Application Home Page after the link has been clicked
     * in the about window.
     * @param evt The MouseEvent to see if the Link has been clicked.
     */
    private void BUWeatherLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BUWeatherLinkMouseClicked
        BarebonesBrowser.openURL("http://weather.bloomu.edu/BUWeatherProject.html",
                this);
}//GEN-LAST:event_BUWeatherLinkMouseClicked

    /**
     * This method will open the class pictures after the link has been clicked
     * in the about window.
     * @param evt The MouseEvent to see if the Link has been clicked.
     */
    private void classPictureLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classPictureLabelMouseClicked
        BarebonesBrowser.openURL("ClassPictures" + File.separator 
                + File.separator + "ClassPictures.html", this);
}//GEN-LAST:event_classPictureLabelMouseClicked

    /**
     * This method will open the Bloomsburg Weather Den after the link as been clicked
     * in the about window.
     * @param evt The MouseEvent to see if the Link has been clicked.
     */
    private void weatherDenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_weatherDenLabelMouseClicked
        BarebonesBrowser.openURL("http://weather.bloomu.edu", this);
    }//GEN-LAST:event_weatherDenLabelMouseClicked

    /**
     * This method will open the license file after the button as been clicked
     * in the about window.
     * @param evt The MouseEvent to see if the Link as been clicked.
     */
    private void licenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseButtonActionPerformed
        try {
            Desktop desktop = null;
            if (Desktop.isDesktopSupported()) {
                desktop = Desktop.getDesktop();
            }
            try {
                desktop.open(licenseFile);
            } catch (IOException ioe) {
                    WeatherLogger.log(Level.WARNING, "Error while trying to load license "
                            + "from the About Window.", ioe);
            }
            noLicenseLabel.setVisible(false);
        } 
        //If the license document doesn't exist
        catch (IllegalArgumentException ex) {
            noLicenseLabel.setVisible(true);
            WeatherLogger.log(Level.WARNING, "The license was not found in the default "
                + "location.", ex);
        }
    }//GEN-LAST:event_licenseButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BUWeatherLink;
    private javax.swing.JLabel OracleLink;
    private javax.swing.JLabel aboutLabel;
    private javax.swing.JPanel attributionPanel;
    private javax.swing.JTextPane attributionsJTextPane;
    private javax.swing.JLabel attributionsLabel;
    private javax.swing.JTextPane authorsJTextPane;
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JLabel classPictureLabel;
    private javax.swing.JLabel copyrightLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton licenseButton;
    private javax.swing.JLabel noLicenseLabel;
    private javax.swing.JLabel weatherDenLabel;
    // End of variables declaration//GEN-END:variables
}
