package weather.clientside.gui.client;

import weather.ApplicationControlSystem;
import weather.common.gui.component.BUDialog;
import weather.common.gui.component.IconProperties;

/**
 * TODO: WINDOW UNDER PROGRESS
 * @author Alex Funk
 * @version 2011
 */
public class CreateAnswerFormDialog extends BUDialog {

    /**
     * Creates a new answer form for a given lesson from the student's
     * instructor.
     * @param applicationControl the ApplicationControlSystem.
     */
    public CreateAnswerFormDialog(ApplicationControlSystem applicationControl) {
        super(applicationControl);
        initComponents();
        setIconImage(IconProperties.getTitleBarIconImage());
        this.setTitle("Weather Viewer - Answer Form for \"Lesson\"");
        super.postInitialize(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underDevelopmentPanel1 = new weather.clientside.gui.administrator.UnderDevelopmentPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(underDevelopmentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(underDevelopmentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private weather.clientside.gui.administrator.UnderDevelopmentPanel underDevelopmentPanel1;
    // End of variables declaration//GEN-END:variables

}
