/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package weather.clientside.gui.client;

import java.awt.Image;
import javax.swing.ImageIcon;
import weather.common.data.lesson.LessonEntry;
import weather.common.data.resource.ImageInstance;
import weather.common.utilities.Debug;
import weather.common.utilities.WeatherException;

/**
 *
 * @author Justin Gamble - 2012
 */
public class LessonEntryImagePanel extends javax.swing.JPanel {
    /**
     * LessonEntry this panel should display an image from.
     */
    private LessonEntry lessonEntry;
    /**
     * Creates new form LessonEntryImagePanel
     */
    public LessonEntryImagePanel(LessonEntry le) {
        initComponents();
        lessonEntry = le;
        //Can't do this with the updated LessonEntry
        ImageInstance icon = lessonEntry.getResourceImage();
        imagePanelLabel.setSize(376, 250);
        Debug.println("imagePanelLabel dims: "+imagePanelLabel.getHeight() + " " + imagePanelLabel.getWidth());
        try{
            imagePanelLabel.setText("");
            imagePanelLabel.setIcon(new ImageIcon(icon.getImage().getScaledInstance(imagePanelLabel.getHeight(), imagePanelLabel.getWidth(), Image.SCALE_SMOOTH)));
        }catch(WeatherException ex){
            ex.show("Image from LessonEntry could not be shown.");
        }
        nameLabel.setText(lessonEntry.getLessonEntryName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new java.awt.Label();
        imagePanel = new javax.swing.JPanel();
        imagePanelLabel = new javax.swing.JLabel();

        nameLabel.setAlignment(java.awt.Label.CENTER);
        nameLabel.setText("nameLabel");

        imagePanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        imagePanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagePanelLabel.setText("No image to display.");

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(imagePanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(imagePanelLayout.createSequentialGroup()
                    .addComponent(imagePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel imagePanel;
    private javax.swing.JLabel imagePanelLabel;
    private java.awt.Label nameLabel;
    // End of variables declaration//GEN-END:variables
}
