package weather.clientside.manager;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.event.ActionListener;
import java.awt.event.WindowListener;
import javax.swing.event.ChangeListener;

/**
 * This window houses the external NotesAndDiaryPanelManager.
 * @author Brian Bankes
 */
public class ExternalNotesForm extends weather.common.gui.component.BUJFrame {
    
    public static final int PERSONAL_NOTES = 0, CLASS_NOTES = 1, DAILY_DIARY = 2;
    
    /**
     * The manager being shown in this form.
     */
    private NotesAndDiaryPanelManager pnlManager;

    /**
     * Creates new form ExternalNotesForm
     */
    public ExternalNotesForm() {
        initComponents();
        int width = 1000 + this.getInsets().left + this.getInsets().right;
        int height = 680 + this.getInsets().top + this.getInsets().bottom;
        Dimension thisDim = new Dimension(width, height);
        this.setSize(thisDim);
        this.setPreferredSize(thisDim);
        this.setMaximumSize(thisDim);
        this.setMinimumSize(thisDim);
        pack();
    }
    
    /**
     * Displays an external window with the personal notes, class notes, and
     * diary panels in it.
     *
     * @param panelFocus The panel to begin focused on.
     * @param pnlManager The NotesAndDiaryPanelManager with all three panels.
     * @param winListener The window listener for the external window.
     * @param changeListener The change listener to attach to the tabbed pane.
     * @param closeListener The action listener for the close button.
     */
    public void displayExternalNotesAndDiaryWindow(int panelFocus, 
            NotesAndDiaryPanelManager pnlManager, WindowListener winListener, 
            ChangeListener changeListener, ActionListener closeListener) {
        this.pnlManager = pnlManager;
        
        //Add header panel.
        pnlTop.add(pnlManager.getHeaderPanel(), 
                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 976, 90));
        
        //Add options and notes panel.
        pnlSide.add(pnlManager.getOptionsAndNotesPanel(),
                new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 531));
        
        //Add tabs.
        pnlManager.externalize();
        pnlManager.setCurrentPane(pnlTabs);
        this.personalNotesPanel.add(pnlManager.getPersonalNotesPanel(), BorderLayout.CENTER);
        this.classNotesPanel.add(pnlManager.getClassNotesPanel(), BorderLayout.CENTER);
        this.dailyDiaryPanel.add(pnlManager.getDiaryPanel(), BorderLayout.CENTER);
        this.pnlTabs.setSelectedIndex(panelFocus);
        this.pnlTabs.addChangeListener(changeListener);
        
        //Add buttons.
        this.pnlButtons.add(pnlManager.getButtonPanel(), BorderLayout.CENTER);
        this.pnlButtons.setVisible(false);
        this.btnClose.addActionListener(closeListener);

        //Set up window.
        addWindowListener(winListener);
        if(panelFocus == DAILY_DIARY){
            btnClose.setVisible(false);
            pnlButtons.setVisible(true);
        }
        super.postInitialize(true);
    }
    
    /**
     * Shows button panel for daily diary.
     */
    public void showButtonPanel(){
        btnClose.setVisible(false);
        pnlButtons.setVisible(true);
        repaint();
    }
    
    /**
     * Show close button for note tabs.
     */
    public void showCloseButton(){
        btnClose.setVisible(true);
        pnlButtons.setVisible(false);
        repaint();
    }
    
    /**
     * Checks if daily diary was selected.
     * @return True is diary selected, false otherwise
     */
    public boolean isDailyDairy(){
        return pnlTabs.getSelectedIndex() == DAILY_DIARY;
    }
    
    /**
     * Checks if personal notes were selected.
     * @return True is personal notes selected, false otherwise
     */
    public boolean isPersonalNotes() {
        return pnlTabs.getSelectedIndex() == PERSONAL_NOTES;
    }
    
    /**
     * Sets main panel to diary.
     */
    public void setToDailyDiary(){
        pnlTabs.setSelectedIndex(DAILY_DIARY);
    }
    
    /**
     * Sets main panel to class notes.
     */
    public void setToClassNotes(){
        pnlTabs.setSelectedIndex(CLASS_NOTES);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlTabs = new javax.swing.JTabbedPane();
        personalNotesPanel = new javax.swing.JPanel();
        classNotesPanel = new javax.swing.JPanel();
        dailyDiaryPanel = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        pnlButtons = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Weather Viewer - Notes and Daily Diary");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, 976, 90));

        personalNotesPanel.setLayout(new java.awt.BorderLayout());
        pnlTabs.addTab("Personal Notes", personalNotesPanel);

        classNotesPanel.setLayout(new java.awt.BorderLayout());
        pnlTabs.addTab("Class Notes", classNotesPanel);

        dailyDiaryPanel.setLayout(new java.awt.BorderLayout());
        pnlTabs.addTab("Daily Diary", dailyDiaryPanel);

        getContentPane().add(pnlTabs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 650, 531));

        btnClose.setText("Close");
        btnClose.setPreferredSize(new java.awt.Dimension(120, 25));
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 645, -1, -1));

        pnlButtons.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 645, 680, 25));

        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 102, 320, 531));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel classNotesPanel;
    private javax.swing.JPanel dailyDiaryPanel;
    private javax.swing.JPanel personalNotesPanel;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JTabbedPane pnlTabs;
    private javax.swing.JPanel pnlTop;
    // End of variables declaration//GEN-END:variables
}
