package weather.serverside.gui.component;

/**
 * Provides a summary of the current amount of storage being used.
 * @author Ty Vanderstappen
 */
public class StorageSummaryPanel extends javax.swing.JPanel {
    
    
    private double maxStorage,currentStorage;
    
    /**
     * Creates new form StorageSummaryPanel
     */
    public StorageSummaryPanel() {
        initComponents();
        
        //test values
        currentStorage=53.5;
        maxStorage=84;
        //progressbar only accepts integers
        storageProgessBar.setMinimum(0);
        storageProgessBar.setValue((int)currentStorage);
        storageProgessBar.setMaximum((int)maxStorage);
        
        double storageLeft = maxStorage-currentStorage;
        double percentLeft = ((84-53.5)/84)*100;
        String percentLeftString = Double.toString(percentLeft).substring(0, 4);
        String currentStorageString = Double.toString(currentStorage).substring(0, 4);
        percentLabel.setText(percentLeftString+"% Remaining");
        storageRemainingLabel.setText(storageLeft+" GB");
        storageProgessBar.setToolTipText(currentStorageString+" GB Used");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storagePanel = new javax.swing.JPanel();
        storageProgessBar = new javax.swing.JProgressBar();
        storageLabel = new javax.swing.JLabel();
        storageRemainingLabel = new javax.swing.JLabel();
        percentLabel = new javax.swing.JLabel();
        dayLabel = new javax.swing.JLabel();
        daysLeftLabel = new javax.swing.JLabel();

        storageLabel.setText("Storage Remaining:");

        storageRemainingLabel.setText("bytes");

        percentLabel.setText("0% Left");

        dayLabel.setText("Days Left Until Full:");

        daysLeftLabel.setText("0 Days");

        javax.swing.GroupLayout storagePanelLayout = new javax.swing.GroupLayout(storagePanel);
        storagePanel.setLayout(storagePanelLayout);
        storagePanelLayout.setHorizontalGroup(
            storagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(storagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(storageProgessBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(storagePanelLayout.createSequentialGroup()
                        .addComponent(storageLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(storageRemainingLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                        .addComponent(percentLabel))
                    .addGroup(storagePanelLayout.createSequentialGroup()
                        .addComponent(dayLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daysLeftLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        storagePanelLayout.setVerticalGroup(
            storagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, storagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(storagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storageLabel)
                    .addComponent(storageRemainingLabel)
                    .addComponent(percentLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(storageProgessBar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(storagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayLabel)
                    .addComponent(daysLeftLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(storagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dayLabel;
    private javax.swing.JLabel daysLeftLabel;
    private javax.swing.JLabel percentLabel;
    private javax.swing.JLabel storageLabel;
    private javax.swing.JPanel storagePanel;
    private javax.swing.JProgressBar storageProgessBar;
    private javax.swing.JLabel storageRemainingLabel;
    // End of variables declaration//GEN-END:variables
}
