package weather.clientside.gui.administrator;

import javax.swing.JOptionPane;
import weather.AdministratorControlSystem;
import weather.clientside.utilities.BarebonesBrowser;
import weather.common.data.diary.DailyDiaryWebLinks;
import weather.common.dbms.DBMSDailyDiaryWebLinkManager;
import weather.common.dbms.DBMSSystemManager;
import weather.common.gui.component.BUDialog;
/**
 *
 * The <code>AddDailyDiaryWebLinks</code> class represents
 * an instance of the Add Daily Diary WebLink window.
 * @author Alinson Antony (2012).
 */


public class AddDailyDiaryWebLinks extends BUDialog {
    //declaration of attributes
    private DBMSSystemManager dbms;
    final private DBMSDailyDiaryWebLinkManager webLinkManager;
    /** 
     * Creates a new AddWebLink window
     * @param adminService The client control object that will allow the window 
     *              to interact with the rest of the program.
     */
    public AddDailyDiaryWebLinks(AdministratorControlSystem adminService) {
        super(adminService);
        dbms = adminService.getGeneralService().getDBMSSystem();
        webLinkManager = dbms.getDailyDiaryWebLinkManager();
        initComponents();
        getRootPane().setDefaultButton(btnAdd);
        weather.clientside.utilities.RightClickMenu.addMenuTo(
                new javax.swing.text.JTextComponent[]{txtName, txtURL});
        
    }
    /**
     * This method is to display default values in name and URL text fields.
     */
     public void displayForAdd() {
         this.clear();
         txtURL.setText("http://www.");
         this.setVisible(true);
     }
     /**
      * This method is to check whether the particular combination of name and
      * URL are already present in the database.
      * @return True if already present otherwise return false.
      */
      private boolean checkURLAndName()
    {
        for(DailyDiaryWebLinks wl :webLinkManager.getLinks())
        {
            if(txtURL.getText().trim().equals(wl.getURLString())&& (txtName.getText().trim().equals(wl.getName())))
            {
               JOptionPane.showMessageDialog(this,"Sorry, Same Combination of Name and URL already exist.");
                return false;
            }
           
        }
        return true;
    }
      /**
       * This method is to be change back to default values in the text fields.
       */
      private void clear() {
         txtURL.setText("http://www.");
         txtName.setText("");
     }


  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        btnTest = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Weather Viewer - Add New Daily Diary Web Link");

        lblName.setText("Name");

        lblURL.setText("URL");

        btnTest.setText("Test URL");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblURL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblURL)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTest))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAdd))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     /**
     *  This method adds a new link to the database. It then clears
     *  the window and waits for more input.
     *  @param evt The event that the add Button was pressed.
     */
   
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         if(this.checkURLAndName()) {
            //webLinkManager.addLink(txtName.getText(),txtURL.getText());
            adminService.repaintWebLink();
            int ans = JOptionPane.showConfirmDialog
                    (this, "WebLink added successfully. Add Another?",
                    "WebLink Successful", JOptionPane.YES_NO_OPTION);
            
            if(ans == JOptionPane.YES_OPTION)
                clear();
            else
                dispose();
        }
    }//GEN-LAST:event_btnAddActionPerformed
     /**
      * This method tests the current URL provided in the URL Text box.
      * @param evt The event that sees if the testURLButton was clicked.
      */
       
    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
       BarebonesBrowser.openURL(txtURL.getText(), this);
    }//GEN-LAST:event_btnTestActionPerformed
     /**
      * This method handles what happens when the user hits the cancel button.
      * @param evt The even the cancelButton is clicked.
      */
       
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnTest;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblURL;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
