package weather.clientside.gui.administrator;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import weather.ApplicationControlSystem;
import weather.common.data.bookmark.CategoryViewRights;
import weather.common.data.lesson.LessonCategory;
import weather.common.dbms.DBMSLessonCategoryManager;
import weather.common.gui.component.BUDialog;

/**
 * The <code>AddLessonCategoryWindow</code> class creates a window
 * for adding new lesson categories.
 * 
 * This window was taken and modified from AddLessonCategoryWindow.
 * Finish the TODO's when lessons are finished on the database.
 * 
 * @author John Lenhart (2012)
 * @author Justin Enslin (2012)
 */
public class AddLessonCategoryWindow extends BUDialog {

    private final ApplicationControlSystem finalClientControl;
    private DBMSLessonCategoryManager categoryManager;

    /** Creates new form AddLessonCategoryWindow */
    public AddLessonCategoryWindow (ApplicationControlSystem appControl) {
        super(appControl);
        finalClientControl = appControl;
        // Initialize vars and components.
        categoryManager = appControl.getDBMSSystem().getLessonCategoryManager();
        initComponents();
        setTitle("Weather Viewer - Create Lesson Category");
        ButtonGroup g = new ButtonGroup();
        g.add(everyoneRadioButton);
        g.add(instructorOnlyRadioButton);
        getRootPane().setDefaultButton(addLessonCategoryButton);
        nameErrorLabel.setVisible(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent evt) {
                close();
            }
        });
        super.postInitialize(false);
    }
    
    /**
     * Helper method that displays the <code>leaveWithoutSaving()</code> dialog.
     */
    private void close(){
        if(!changed() || appControl.getGeneralService()
                .leaveWithoutSaving(this))
            dispose();
    }
    
    /**
     * Helper method to determine whether or not something has been changed in 
     * the window.
     * 
     * @return True if something was changed, false otherwise.
     */
    private boolean changed(){
        return !(nameTextField.getText().isEmpty() && 
                noteTextPane.getText().isEmpty() && 
                everyoneRadioButton.isSelected());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        noteLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        noteTextPane = new javax.swing.JTextPane();
        addLessonCategoryButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        maxNameLabel = new javax.swing.JLabel();
        maxNoteLabel = new javax.swing.JLabel();
        rightsLabel = new javax.swing.JLabel();
        everyoneRadioButton = new javax.swing.JRadioButton();
        instructorOnlyRadioButton = new javax.swing.JRadioButton();
        nameErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Weather Viewer - Add New Lesson Category ");

        nameLabel.setText("Category Name:");

        noteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        noteLabel.setText("Description:");

        jScrollPane1.setViewportView(noteTextPane);

        addLessonCategoryButton.setText("Add Lesson Category");
        addLessonCategoryButton.setToolTipText("Create the new Lesson Category");
        addLessonCategoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonCategoryButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Close");
        cancelButton.setToolTipText("Closes the window without saving");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        maxNameLabel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        maxNameLabel.setText("(max 100 char)");

        maxNoteLabel.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        maxNoteLabel.setText("(max 250 char)");

        rightsLabel.setText("View Rights:");
        rightsLabel.setToolTipText("Allows the ability to select if everyone can view the category or just the instructor");

        everyoneRadioButton.setSelected(true);
        everyoneRadioButton.setText("Everyone");

        instructorOnlyRadioButton.setText("Private");

        nameErrorLabel.setForeground(new java.awt.Color(204, 0, 0));
        nameErrorLabel.setText("Category Must Have A Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel)
                            .addComponent(noteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rightsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(everyoneRadioButton)
                                .addGap(16, 16, 16)
                                .addComponent(instructorOnlyRadioButton))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(nameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLessonCategoryButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameErrorLabel)
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(maxNoteLabel)
                        .addComponent(maxNameLabel))
                    .addComponent(cancelButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxNameLabel)
                    .addComponent(nameLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(maxNoteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noteLabel)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rightsLabel)
                    .addComponent(everyoneRadioButton)
                    .addComponent(instructorOnlyRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(addLessonCategoryButton)
                    .addComponent(nameErrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addLessonCategoryButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonCategoryButtonActionPerformed
        LessonCategory category;
        String name, note;
        boolean success = false;

        // Get text from inputs.
        name = nameTextField.getText ().trim();
        if (name.isEmpty()){
            nameErrorLabel.setVisible(true);
        }
        note = noteTextPane.getText ().trim();
        
        CategoryViewRights viewRights;
        if(everyoneRadioButton.isSelected())
            viewRights = CategoryViewRights.system_wide;
        else viewRights = CategoryViewRights.instructor_only;
        
        category=new LessonCategory(-1, name, appControl.getGeneralService().getUser().getUserNumber(), viewRights, -1);
        category.setInstructorNumber(appControl.getGeneralService().getUser().getUserNumber());
        
        success =categoryManager.add(category);
        if (success) {
            JOptionPane.showMessageDialog (this, "Lesson Category Added Successfully",
                    "Lesson Category Added", JOptionPane.INFORMATION_MESSAGE);
            dispose ();
        }
        else {
            JOptionPane.showMessageDialog (this, "Lesson Category Failed to Be Added",
                    "Lesson Category Not Added", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_addLessonCategoryButtonActionPerformed

    private void cancelButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        close();
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addLessonCategoryButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton everyoneRadioButton;
    private javax.swing.JRadioButton instructorOnlyRadioButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel maxNameLabel;
    private javax.swing.JLabel maxNoteLabel;
    private javax.swing.JLabel nameErrorLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel noteLabel;
    private javax.swing.JTextPane noteTextPane;
    private javax.swing.JLabel rightsLabel;
    // End of variables declaration//GEN-END:variables

}
