package weather.clientside.gui.administrator;

import javax.swing.JOptionPane;
import weather.AdministratorControlSystem;
import weather.clientside.utilities.BarebonesBrowser;
import weather.common.data.diary.DailyDiaryWebLinks;
import weather.common.dbms.DBMSDailyDiaryWebLinkManager;
import weather.common.dbms.DBMSSystemManager;
import weather.common.gui.component.BUDialog;

/**
 * The <code>EditDailyDiaryWebLinks</code> class represents an
 * instance of the EditDailyDiaryWebLinks. This allows an administrator 
 * to choose a link to edit. 
 * @author Alinson Antony(2012).
 * 
 */
public class EditDailyDiaryWebLinks extends BUDialog {
    private DBMSSystemManager dbms;
    private DBMSDailyDiaryWebLinkManager webLinkManager;
    private String savecheckerurl;
  /**
   * Constructor for the class EditDailyDiaryWebLinks.
   * @param adminService The GeneralService object that communicates with other 
     *              parts of the program.
   * @param name Name of the link.
   * @param URL  Link URL.
   */
   public EditDailyDiaryWebLinks(AdministratorControlSystem adminService,String name,String URL,String linkNumber) {
       super(adminService);
       this.dbms = adminService.getGeneralService().getDBMSSystem();
       webLinkManager = dbms.getDailyDiaryWebLinkManager();
       initComponents();
       txtName.setText(name);
       txtURL.setText(URL);
       txtLinkNumber.setText(linkNumber);
       this.pack();
       this.savecheckerurl = URL;
       super.postInitialize(false);
    }

  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblURL = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtURL = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnTest = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblLinkNumber = new javax.swing.JLabel();
        txtLinkNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Weather Viewer - Edit Daily Diary Web Links");

        lblName.setText("Name");

        lblURL.setText("URL");

        txtName.setEditable(false);

        btnUpdate.setText("Update Link");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnTest.setText("Test URL");
        btnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTestActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblLinkNumber.setText("Number");

        txtLinkNumber.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUpdate))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblURL)
                            .addComponent(lblLinkNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtLinkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 196, Short.MAX_VALUE))
                            .addComponent(txtURL)
                            .addComponent(txtName))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnTest))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLinkNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLinkNumber))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTest)
                    .addComponent(lblURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnClose))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        boolean isSuccessfull = false;
        DailyDiaryWebLinks linkToUpdate = new DailyDiaryWebLinks(0,null,null);
         linkToUpdate.setName(txtName.getText());
         linkToUpdate.setURL(txtURL.getText());
         linkToUpdate.setLinkNumber(Integer.parseInt(txtLinkNumber.getText().trim()));
        if (linkToUpdate != null) {
           isSuccessfull = webLinkManager.updateLink(linkToUpdate);
        } else {
           JOptionPane.showMessageDialog(this, "WebLink not updated successfully.");
        }
        if(isSuccessfull) {
            JOptionPane.showMessageDialog(this, "WebLink updated successfully.");
            dispose();
        }else {
            JOptionPane.showMessageDialog(this, "WebLink not updated successfully.");
            dispose();
        }

        this.adminService.repaintWebLink();
  
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTestActionPerformed
         BarebonesBrowser.openURL(txtURL.getText(), this);
    }//GEN-LAST:event_btnTestActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        if(!(savecheckerurl.trim().equals(txtURL.getText().trim())))
       {
               if(adminService.getGeneralService().leaveWithoutSaving(this))
                {
                    dispose();
                }
           } 
           else {
                dispose();
           }
       
    }//GEN-LAST:event_btnCloseActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnTest;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblLinkNumber;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblURL;
    private javax.swing.JTextField txtLinkNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
