package weather.clientside.gui.administrator;

import java.util.Calendar;
import javax.swing.JOptionPane;
import weather.ApplicationControlSystem;
import weather.clientside.gradebook.GBCourseEntry;
import weather.clientside.gradebook.GBStudentEntry;
import weather.common.utilities.CommonLocalFileManager;
import weather.common.gui.component.BUDialog;

/**
 * Dialog box gives user options to save part or entire gradebook to an excel
 * file. User will have the option to export specific entries or entire
 * gradebook. They can also select details they want to be exported to their
 * excel file. Optional custom filename also available.
 *
 * @author Nikita Maizet
 */
public class ExportToCSVDialog extends BUDialog {

    private GBCourseEntry courseEntry;
    private GBStudentEntry studentEntry;
    private int[] selectedStudents;
    private boolean exportSingleStudentOnly;

    /**
     * Creates new export to CSV dialog.
     *
     * @param appControl ApplicationControlSystem instance
     * @param courseEntry GBCourse entry used to obtain data to be written to
     * file
     * @param selectedStudents array of indexes of the student(s) to be exported
     * to file
     */
    public ExportToCSVDialog(ApplicationControlSystem appControl,
            GBCourseEntry courseEntry, int[] selectedStudents) {
        super(appControl);

        this.setTitle("Export Gradebook to Excel Options");
        this.courseEntry = courseEntry;
        this.selectedStudents = selectedStudents;
        this.exportSingleStudentOnly = false;

        initComponents();
        initialize();

        postInitialize(false);
    }

    private void initialize() {
        Calendar cal = Calendar.getInstance();
        String defaultFilename;

        if (exportSingleStudentOnly) {
            defaultFilename = studentEntry.getLastName() + "_"
                    + studentEntry.getFirstName() + "_"
                    + (cal.get(Calendar.MONTH) + 1) + "."
                    + cal.get(Calendar.DAY_OF_MONTH) + "."
                    + cal.get(Calendar.YEAR) + ".xlsx";

            // disable export options for only a student entry:
            exportFinalGradesCheckbox.setEnabled(false);
            exportIndividualLessonsCheckbox.setEnabled(false);

        } else {
            defaultFilename = courseEntry.getCourse().getClassIdentifier()
                    + "_0" + courseEntry.getCourse().getSection()
                    + "_" + courseEntry.getCourse().getClassName() + "_"
                    + (cal.get(Calendar.MONTH) + 1) + "."
                    + cal.get(Calendar.DAY_OF_MONTH) + "."
                    + cal.get(Calendar.YEAR) + ".xlsx";
        }

        fileNameTextField.setText(defaultFilename);
        filePathTextField.setText(CommonLocalFileManager.getForecastingLessonExcelFilesDirectory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exportButtonGroup = new javax.swing.ButtonGroup();
        exportDetailsLabel = new javax.swing.JLabel();
        fileNameLabel = new javax.swing.JLabel();
        fileNameTextField = new javax.swing.JTextField();
        filePathLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        filePathTextField = new javax.swing.JTextField();
        exportFinalGradesCheckbox = new java.awt.Checkbox();
        exportIndividualLessonsCheckbox = new java.awt.Checkbox();

        exportDetailsLabel.setText("Export Options:");

        fileNameLabel.setText("File Name:");

        fileNameTextField.setText("<Enter File Name Here>");
        fileNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fileNameTextFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fileNameTextFieldFocusLost(evt);
            }
        });

        filePathLabel.setText("Save to:");

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        exportButton.setText("Export");
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        filePathTextField.setText("C:\\");
            filePathTextField.setEnabled(false);

            exportFinalGradesCheckbox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
            exportFinalGradesCheckbox.setLabel("Export Final Grades");
            exportFinalGradesCheckbox.setName("Export Final Grades"); // NOI18N

            exportIndividualLessonsCheckbox.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
            exportIndividualLessonsCheckbox.setLabel("Export Individual Test Lesson Grades");

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(fileNameLabel)
                                        .addGap(51, 51, 51))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(filePathLabel)
                                        .addGap(43, 43, 43)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(exportDetailsLabel)
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fileNameTextField)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(exportFinalGradesCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(exportIndividualLessonsCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 120, Short.MAX_VALUE))
                                .addComponent(filePathTextField))))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(exportDetailsLabel)
                        .addComponent(exportFinalGradesCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(exportIndividualLessonsCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fileNameLabel)
                        .addComponent(fileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(filePathLabel)
                        .addComponent(filePathTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton)
                        .addComponent(exportButton))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void fileNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fileNameTextFieldFocusGained

    }//GEN-LAST:event_fileNameTextFieldFocusGained

    private void fileNameTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fileNameTextFieldFocusLost

    }//GEN-LAST:event_fileNameTextFieldFocusLost

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        if (exportSingleStudentOnly) {
            studentEntry.exportToExcel(fileNameTextField.getText());
        } else {
            if (exportFinalGradesCheckbox.getState() && exportIndividualLessonsCheckbox.getState()) {
                courseEntry.exportToCSVWithCourseSummary(selectedStudents, fileNameTextField.getText());
                this.dispose();
            } else if (exportFinalGradesCheckbox.getState()) {
                courseEntry.exportToCSVCourseSummaryOnly(selectedStudents, fileNameTextField.getText());
                this.dispose();
            } else if (exportIndividualLessonsCheckbox.getState()) {
                courseEntry.exportToCSVStudentDetailsOnly(selectedStudents, fileNameTextField.getText());
                this.dispose();
            } else // show error message since no selection
            {
                JOptionPane.showMessageDialog(this, "Please make a export options selection!");
            }
        }

    }//GEN-LAST:event_exportButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton exportButton;
    private javax.swing.ButtonGroup exportButtonGroup;
    private javax.swing.JLabel exportDetailsLabel;
    private java.awt.Checkbox exportFinalGradesCheckbox;
    private java.awt.Checkbox exportIndividualLessonsCheckbox;
    private javax.swing.JLabel fileNameLabel;
    private javax.swing.JTextField fileNameTextField;
    private javax.swing.JLabel filePathLabel;
    private javax.swing.JTextField filePathTextField;
    // End of variables declaration//GEN-END:variables
}
