package weather.clientside.gui.administrator;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import weather.ApplicationControlSystem;
import weather.clientside.utilities.MyDefaultTableModel;
import weather.common.data.User;
import weather.common.data.lesson.LessonCategory;
import weather.common.dbms.DBMSLessonCategoryManager;
import weather.common.dbms.DBMSUserManager;
import weather.common.gui.component.BUDialog;

/**
 * The <code>InstructionLessons</code> window creates a form that 
 * lists all lesson Categories available.
 * 
 * @author Ty Vanderstappen (2012)
 * @author Justin Enslin (2012)
 * @author John Lenhart (2012)
 * @version 2012
 */
public class InstructionLessons extends BUDialog {

    //used to determine how many columns in the table there are
    private static int TABLE_LENGTH = 1;
    public static int NAME_COLUMN = 0;
    private int categoryType;
    
    private MyDefaultTableModel lessonModel;
    private TableRowSorter<MyDefaultTableModel> lessonSorter;
    
    private DBMSUserManager userManager;
    private DBMSLessonCategoryManager categoryManager;
    private Vector<LessonCategory> lessonCategories;
    
    
    /**
     * Creates a new Open Lessons window displaying all lessonCategories the
     * current user can edit.
     * 
     * @param appControl The application control system.
     */
    public InstructionLessons(ApplicationControlSystem appControl) 
    {
        super(appControl);
        initComponents();
        initialize(appControl);
        super.postInitialize(true);
    }
    
    /**
     * Helper method containing common initialization code.
     * 
     * @param appControl The application control system.
     */
    private void initialize(final ApplicationControlSystem appControl){
        errorLabel.setVisible(false);
        
        userManager = appControl.getDBMSSystem().getUserManager();
        categoryManager = appControl.getDBMSSystem().getLessonCategoryManager();

        setTitle("Weather Viewer - Open Lessons");
        updateTable();
        MouseAdapter doubleClick = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                JTable target = (JTable) e.getSource();
                if (e.getClickCount() == 2){
                    int row = target.getSelectedRow();
                    String name = target.getValueAt(row, NAME_COLUMN).toString();
                    for(LessonCategory cat : lessonCategories)
                        if(cat.getName().equals(name))
                            categoryType = cat.getLessonCategoryNumber();
                    new ViewLessons(appControl,categoryType);
                }
            }
        };
        lessonTable.addMouseListener(doubleClick);
        
        /*//Center the column.
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        lessonTable.getColumnModel().getColumn(NAME_COLUMN).setCellRenderer( centerRenderer );*/
        
        //Center the header.
        TableCellRenderer renderer = lessonTable.getTableHeader().getDefaultRenderer();
        JLabel label = (JLabel)renderer;
        label.setHorizontalAlignment(JLabel.CENTER);
    }
    
    /**
     * Updates the table.
     */
    private void updateTable() {
        User currentUser = appControl.getGeneralService().getUser();
        lessonCategories = categoryManager.obtainAll();
        
        //Set column model and sorter
        lessonModel = new MyDefaultTableModel(0, 0);
        lessonModel.setColumnCount(TABLE_LENGTH);
        lessonModel.setRowCount(lessonCategories.size());
        lessonTable.setModel(lessonModel);
        lessonSorter = new TableRowSorter<MyDefaultTableModel>(lessonModel);
        lessonTable.setRowSorter(lessonSorter);
        
        //Set column names
        lessonTable.getColumnModel().getColumn(NAME_COLUMN).
                setHeaderValue("Category");
        
        //Add lessonCategories
        for(int i=0; i<lessonCategories.size(); i++){
            LessonCategory lessonCategory = lessonCategories.get(i);
            lessonTable.setValueAt(lessonCategory.getName(), i, NAME_COLUMN);
        }
        
        //Grab row filters if search window exists
        
        lessonTable.revalidate();
        validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lessonScrollPanel = new javax.swing.JScrollPane();
        lessonTable = new javax.swing.JTable();
        closeButton = new javax.swing.JButton();
        editLabel = new javax.swing.JLabel();
        openButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();

        setTitle("Weather Viewer - Open Lessons");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        lessonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        lessonScrollPanel.setViewportView(lessonTable);

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        editLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        editLabel.setText("Double click to open lesson category.");

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText("No Category Selected");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(openButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(editLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(closeButton))
                        .addComponent(lessonScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(errorLabel))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lessonScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(editLabel)
                    .addComponent(openButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The Open Lessons window will close.
     * @param evt 
     */
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        updateTable();
    }//GEN-LAST:event_formWindowGainedFocus

    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        if(lessonTable.getSelectedRowCount()==0){
            errorLabel.setVisible(true);
        }
        else{
            errorLabel.setVisible(false);
            int row = lessonTable.getSelectedRow();
            String name = lessonTable.getValueAt(row, NAME_COLUMN).toString();
            for(LessonCategory cat : lessonCategories)
                if(cat.getName().equals(name))
                    categoryType = cat.getLessonCategoryNumber();
            new ViewLessons(appControl,categoryType);
        }
    }//GEN-LAST:event_openButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel editLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JScrollPane lessonScrollPanel;
    private javax.swing.JTable lessonTable;
    private javax.swing.JButton openButton;
    // End of variables declaration//GEN-END:variables
}
