package weather.clientside.gui.administrator;

import javax.swing.JOptionPane;
import weather.AdministratorControlSystem;
import weather.clientside.gui.administrator.SearchForAUserDialog.SEARCH_TYPES;
import weather.common.gui.component.BUDialog;

/**
 * The <code>SearchUserWindow</code> class is a test idea for a new edit 
 * user window.  Basically the user will be allowed to enter in the name 
 * of the user they want to edit, or they can click the search button 
 * which will take them to a search screen which they can search for 
 * specific user types and be given a table of users under that user type.
 *
 * @author Bloomsburg University Software Engineering
 * @author Ora Merkel (2009)
 * @author Joe Van Lente (2010)
 * @author Alex Funk (2011)
 *
 * @version Spring 2011
 */
public class SearchUserWindow extends BUDialog {
    
    private boolean isAdmin;
    
    /**
     * Constructor for the edit user window, for administrative purposes.
     * @param adminService the GerneralService object that allows this class to communicate
     * with other parts of the program.
     * @param isAdmin True if listing should have administrative ability to 
     * see and edit more than students and guests, false otherwise.
     */
    public SearchUserWindow(AdministratorControlSystem adminService, boolean isAdmin) {
        super(adminService);
        initComponents();
        this.isAdmin = isAdmin;
        pack();

        getRootPane().setDefaultButton(okButton);
        weather.clientside.utilities.RightClickMenu.addMenuTo(searchField);
        searchButtonGroup.add(searchByFNameButton);
        searchButtonGroup.add(searchByLNameButton);
        searchButtonGroup.add(searchByUserIDButton);
        searchButtonGroup.setSelected(searchByUserIDButton.getModel(), true);
        searchLabel.setText("Login ID:");
        searchLabel.setToolTipText("The user login identification");
        searchField.setToolTipText("The user login identification");
        searchField.requestFocus();
        super.postInitialize(false);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButtonGroup = new javax.swing.ButtonGroup();
        okButton = new javax.swing.JButton();
        searchByFNameButton = new javax.swing.JRadioButton();
        searchByLNameButton = new javax.swing.JRadioButton();
        searchByUserIDButton = new javax.swing.JRadioButton();
        searchOptionsPanel = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        searchLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();

        setTitle("Weather Viewer - Search For User");
        setBounds(new java.awt.Rectangle(300, 300, 0, 0));
        setModal(true);
        setResizable(false);

        okButton.setText("Search");
        okButton.setToolTipText("Edit selected user");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        searchByFNameButton.setText("Search By User's First Name");
        searchByFNameButton.setToolTipText("Search for a user by first name");
        searchByFNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByFNameButtonActionPerformed(evt);
            }
        });

        searchByLNameButton.setText("Search By User's Last Name");
        searchByLNameButton.setToolTipText("Search for a user by last name");
        searchByLNameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByLNameButtonActionPerformed(evt);
            }
        });

        searchByUserIDButton.setText("Search By User's Login Identification");
        searchByUserIDButton.setToolTipText("Search for a user by user identification");
        searchByUserIDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchByUserIDButtonActionPerformed(evt);
            }
        });

        searchField.setToolTipText("Enter user name to edit.");

        searchLabel.setText("User Name:");

        javax.swing.GroupLayout searchOptionsPanelLayout = new javax.swing.GroupLayout(searchOptionsPanel);
        searchOptionsPanel.setLayout(searchOptionsPanelLayout);
        searchOptionsPanelLayout.setHorizontalGroup(
            searchOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchOptionsPanelLayout.setVerticalGroup(
            searchOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchOptionsPanelLayout.createSequentialGroup()
                .addGroup(searchOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchLabel)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cancelButton.setText("Close");
        cancelButton.setToolTipText("Closes this window.");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchByLNameButton)
                            .addComponent(searchByFNameButton)
                            .addComponent(searchByUserIDButton))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(okButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                                .addComponent(cancelButton)
                                .addGap(13, 13, 13))
                            .addComponent(searchOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchByFNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByLNameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByUserIDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cancelButton, okButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Event handler method for when the Cancel button is pressed in the
     * searchForUser window. It displays a message to the user and closes the window.
     * @param evt The ActionEvent that checks to see if the "Cancel" button was pressed.
     */
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        if (searchField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "You did not enter valid "
                    + "input for " + searchLabel.getText(),
                    "Invalid Entry", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if (searchByUserIDButton.isSelected()){
                adminService.getSpecificUserList(searchField.getText(), SEARCH_TYPES.LOGIN_ID,
                        isAdmin);
            }
            else if (searchByLNameButton.isSelected()){
                adminService.getSpecificUserList(searchField.getText(), SEARCH_TYPES.LAST_NAME,
                        isAdmin);
            }
            else if (searchByFNameButton.isSelected()){
                adminService.getSpecificUserList(searchField.getText(), SEARCH_TYPES.FIRST_NAME,
                        isAdmin);
            }
            searchField.setText("");
            searchField.requestFocus();
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void searchByFNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByFNameButtonActionPerformed
        searchLabel.setText("First Name:");
        searchLabel.setToolTipText("The first name of the user");
        searchField.setToolTipText("The first name of the user");
        searchField.setText("");
        searchField.requestFocus();
    }//GEN-LAST:event_searchByFNameButtonActionPerformed

    private void searchByLNameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByLNameButtonActionPerformed
        searchLabel.setText("Last Name:");
        searchLabel.setToolTipText("The last name of the user");
        searchField.setToolTipText("The last name of the user");
        searchField.setText("");
        searchField.requestFocus();
    }//GEN-LAST:event_searchByLNameButtonActionPerformed

    private void searchByUserIDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchByUserIDButtonActionPerformed
        searchLabel.setText("Login ID:");
        searchLabel.setToolTipText("The user login identification");
        searchField.setToolTipText("The user login identification");
        searchField.setText("");
        searchField.requestFocus();
    }//GEN-LAST:event_searchByUserIDButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton okButton;
    private javax.swing.ButtonGroup searchButtonGroup;
    private javax.swing.JRadioButton searchByFNameButton;
    private javax.swing.JRadioButton searchByLNameButton;
    private javax.swing.JRadioButton searchByUserIDButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    private javax.swing.JPanel searchOptionsPanel;
    // End of variables declaration//GEN-END:variables
}
