package weather.clientside.gui.administrator;

import weather.clientside.gui.client.RandomFactsGenerator;
import weather.common.gui.component.IconProperties;

/**
 * This panel was created to use for any window that is currently under
 * development or have not been developed yet.
 * @author Alex Funk
 * @version 2011
 */
public class UnderDevelopmentPanel extends javax.swing.JPanel {

    /** Creates new form UnderDevelopmentPanel */
    public UnderDevelopmentPanel() {
        super();
        initComponents();
        randomFactLabel.setText("<html>"+RandomFactsGenerator.getFact()+
                "</html>");
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underDevlopmentLabel = new javax.swing.JLabel();
        didKnowLabel = new javax.swing.JLabel();
        randomFactLabel = new javax.swing.JLabel();

        underDevlopmentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        underDevlopmentLabel.setText("This window is currently under development.");

        didKnowLabel.setIcon(IconProperties.getInformationIcon());
        didKnowLabel.setText("Did you know?");

        randomFactLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        randomFactLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(randomFactLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(didKnowLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(underDevlopmentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(underDevlopmentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(didKnowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(randomFactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel didKnowLabel;
    private javax.swing.JLabel randomFactLabel;
    private javax.swing.JLabel underDevlopmentLabel;
    // End of variables declaration//GEN-END:variables

}
