package weather.clientside.gui.administrator;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import weather.AdministratorControlSystem;
import weather.clientside.utilities.BarebonesBrowser;
import weather.common.gui.component.BUDialog;

/**
 * The <code>URLTester</code> class creates a form that allows the 
 * administrator to test a URL to make sure it is valid.
 * Currently, it appears to only check if it is a valid URL, but no check is
 * performed to see if it is one that it can retrieve resources with.
 * @author  David Lusby
 * @author Ora Merkel (2009)
 * @author Bloomsburg University Software Engineering
 * @version Spring 2008
 */
public class URLTester extends BUDialog {
    /*
     * The administrator service this window will use.
     */
    AdministratorControlSystem adminService;

    
    /** 
     * Creates new form URLTester. 
     * @param adminService The administrator service this window will use.
     */
    public URLTester(AdministratorControlSystem adminService)
    {
        super();
        this.setTitle("URL Tester");
        this.setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();

        textURL.setCaretPosition(11);
        this.adminService = adminService;
        weather.clientside.utilities.RightClickMenu.addMenuTo(textURL);
        super.postInitialize(true);
    }
    
    /** 
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        url_JLabel = new javax.swing.JLabel();
        textURL = new javax.swing.JTextField();
        buttonTest = new javax.swing.JButton();
        close_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Weather Viewer - URL Tester");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        url_JLabel.setText("URL:");

        textURL.setText("http://www.");
        textURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textURLKeyPressed(evt);
            }
        });

        buttonTest.setText("Test URL");
        buttonTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTestActionPerformed(evt);
            }
        });
        buttonTest.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonTestKeyPressed(evt);
            }
        });

        close_Button.setText("Close");
        close_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_ButtonActionPerformed(evt);
            }
        });
        close_Button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                close_ButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(close_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(url_JLabel)
                        .addGap(4, 4, 4)
                        .addComponent(textURL, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonTest, close_Button});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(url_JLabel)
                    .addComponent(textURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTest)
                    .addComponent(close_Button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonTest, close_Button});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method is called when the Test URL button is clicked.
     * The URL is opened in a new browser window.
     * @param evt The event that the Test URL button is clicked.
     */
    private void buttonTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTestActionPerformed
            BarebonesBrowser.openURL(textURL.getText(), this);
}//GEN-LAST:event_buttonTestActionPerformed

    /**
     * This method is called when the cancel button is clicked.
     * The window is closed.
     * @param evt The event that the cancel button is clicked.
     */
    private void close_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_ButtonActionPerformed
        textURL.setText("");
        this.dispose();
}//GEN-LAST:event_close_ButtonActionPerformed

    /**
     * This method is called when the return key is pressed while focus is on
     * the URL TextBox. The URL is opened in a new browser window.
     * @param evt The event that the enter key is pressed while focus is on the
     * URL TextBox.
     */
    private void textURLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textURLKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
           BarebonesBrowser.openURL(textURL.getText(), this);
        }
    }//GEN-LAST:event_textURLKeyPressed

     /**
     * This method is called when the return key is pressed while focus is on
     * the test URL button. The URL is opened in a new browser window.
     * 
     * @param evt The event that the enter key is pressed while focus is on the
     * test URL button.
     */
    private void buttonTestKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonTestKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
           BarebonesBrowser.openURL(textURL.getText(), this);
        }
    }//GEN-LAST:event_buttonTestKeyPressed

      /**
     * This method is called when the return key is pressed while focus is on
     * the cancel button.
     * 
     * @param evt The event that the enter key is pressed while focus is on the
     * cancel button. the window is closed.
     */
    private void close_ButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_close_ButtonKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER )
        {
           textURL.setText("");
           this.dispose();
        }
    }//GEN-LAST:event_close_ButtonKeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTest;
    private javax.swing.JButton close_Button;
    private javax.swing.JTextField textURL;
    private javax.swing.JLabel url_JLabel;
    // End of variables declaration//GEN-END:variables
    
}
