DROP TABLE IF EXISTS `testTable`;
CREATE TABLE IF NOT EXISTS `testTable` (
  `linkNumber` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `URL` varchar(100) NOT NULL,
  `type` enum('LINK','FORECAST') NOT NULL DEFAULT 'LINK',
  `linkCategoryNumber` int(10) NOT NULL,
  `orderRank` int(11) NOT NULL,
  PRIMARY KEY (`linkNumber`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=272 ;

INSERT INTO `testTable` (`linkNumber`, `name`, `URL`, `type`, `linkCategoryNumber`, `orderRank`) VALUES
(29, 'The National Hurricane Center - NHC', 'http://www.nhc.noaa.gov/', 'LINK', 0, 0),
(30, 'The National Climatic Data Center - NCDC', 'http://www.ncdc.noaa.gov/oa/ncdc.html', 'LINK', 0, 1),
(32, 'The Weather Matrix', 'http://www.weathermatrix.com/', 'LINK', 0, 2),
(49, 'NWS - Bloomsburg', 'http://forecast.weather.gov/MapClick.php?zoneid=PAZ053', 'FORECAST', 0, 3),
(50, 'NOAA Weather Radio - Wilkes-Barre', 'http://audioplayer.wunderground.com', 'FORECAST', 0, 4),
(51, 'Weather Underground - KPABLOOM4', 'http://www.wunderground.com/weatherstation/WXDailyHistory.asp?ID=KPABLOOM4', 'FORECAST', 0, 5),
(57, 'Bloomsburg University', 'http://www.bloomu.edu/', 'LINK', 0, 6),
(58, 'The Cloud Appreciation Society', 'http://cloudappreciationsociety.org/', 'LINK', 0, 7),
(61, 'The Weather Den Current Condition', 'http://organizations.bloomu.edu/weather/', 'FORECAST', 0, 8),
(63, 'The Weather Den(Class Website)', 'http://organizations.bloomu.edu/weather/ClassDirectory/ClassWebpage.html', 'LINK', 0, 9),
(64, 'The Weather Den Homepage', 'http://weather.bloomu.edu/', 'LINK', 0, 10),
(140, 'Intellicast Interactive Map', 'http://www.intellicast.com/Local/Map.aspx', 'LINK', 2, 11),
(141, 'Weather Underground – Wundermap', 'http://www.wunderground.com/wundermap/?lat=42.39101&lon=-77.65137&zoom=3', 'LINK', 2, 12),
(142, 'AccuWeather Enhanced Radar', 'http://www.accuweather.com/enhanced-radar.asp?partner=accuweather&traveler=0', 'LINK', 2, 13),
(143, 'NWS – National Radar', 'http://www.nws.noaa.gov/radar_tab.php', 'LINK', 3, 14),
(144, 'Intellicast – National Radar', 'http://www.intellicast.com/National/Radar/Current.aspx', 'LINK', 3, 15),
(145, 'AccuWeather – National Radar', 'http://www.accuweather.com/index-radar.asp?partner=accuweather&traveler=0', 'LINK', 3, 16),
(146, 'Global Infrared – Intellicast', 'http://www.intellicast.com/Global/Satellite/Infrared.aspx', 'LINK', 4, 17),
(147, 'U.S. National Infrared – NWS', 'http://www.goes.noaa.gov/', 'LINK', 4, 18),
(148, 'U.S. National Infrared – Intellicast', 'http://www.intellicast.com/National/Satellite/Infrared.aspx', 'LINK', 4, 19),
(149, 'U.S. National Infrared – AccuWeather', 'http://www.accuweather.com/maps-satellite.asp?partner=accuweather&traveler=0&type=ei ', 'LINK', 4, 20),
(150, 'U.S. Visible Satellite – NWS', 'http://www.goes.noaa.gov/', 'LINK', 4, 21),
(151, 'U.S. Visible Satellite – Intellicast', 'http://www.intellicast.com/National/Satellite/Visible.aspx', 'LINK', 4, 22),
(152, 'U.S. Visible Satellite – AccuWeather', 'http://www.accuweather.com/maps-satellite.asp?partner=accuweather&traveler=0&zipcode=&type=vis ', 'LINK', 4, 23),
(153, 'U.S. Water Vapor – NWS', 'http://www.goes.noaa.gov/', 'LINK', 11, 24),
(154, 'U.S. Water Vapor – Intellicast', 'http://www.intellicast.com/National/Satellite/Visible.aspx', 'LINK', 4, 25),
(155, 'U.S. Water Vapor – AccuWeather', 'http://www.accuweather.com/maps-satellite.asp?partner=accuweather&traveler=0&zipcode=&type=wv ', 'LINK', 2, 26),
(156, 'Watches and Warnings', 'http://www.weather.gov/', 'LINK', 11, 27),
(157, 'National Hurricane Center', 'http://www.nhc.noaa.gov/', 'LINK', 11, 28),
(159, 'National Climatic Data Center', 'http://www.nhc.noaa.gov/', 'LINK', 11, 29),
(173, 'Cloud Appreciation Society', 'http://cloudappreciationsociety.org/', 'LINK', 5, 30),
(176, 'NWS JetStream School', 'http://www.srh.noaa.gov/jetstream/synoptic/clouds.htm', 'LINK', 5, 31),
(177, 'Clouds Online', 'http://www.clouds-online.com/', 'LINK', 5, 32),
(178, 'NWS Surface Map', 'http://www.nws.noaa.gov/outlook_tab.php', 'LINK', 6, 33),
(179, 'Intellicast Surface Map', 'http://www.intellicast.com/National/Surface/Forcast12.aspx', 'LINK', 6, 34),
(180, 'Weather Underground Surface Map', 'http://www.wunderground.com/US/Region/US/Fronts.html', 'LINK', 6, 35),
(181, 'The Weather Channel Surface Map', 'http://www.weather.com/maps/news/forecastsummary/uscurrentweather_large.html', 'LINK', 6, 36),
(182, 'Online Weather Studies Surface Map', 'http://www.ametsoc.org/amsedu/dstreme/images/sfc_map.gif', 'LINK', 6, 37),
(183, 'Online Weather Studies Surface Map', 'http://www.ametsoc.org/amsedu/dstreme/images/sfcpmap.gif', 'LINK', 7, 38),
(184, 'Unisys Surface Data', 'http://weather.unisys.com/surface/sfc_map.html', 'LINK', 7, 39),
(185, 'NWS Sample Station Model Plot', 'http://www.hpc.ncep.noaa.gov/html/stationplot.shtml', 'LINK', 7, 40),
(186, 'Online Weather Studies - Stuve Diagram', 'http://www.ametsoc.org/amsedu/dstreme/stuve.html', 'LINK', 8, 41),
(187, 'UBC - Upper Air Resources', 'http://www.eos.ubc.ca/courses/atsc201/BrooksCole/MetSciEngr/SoundingsStabilityLab.html', 'LINK', 8, 42),
(190, 'Introductory Meteorology Modules', 'http://people.cas.sc.edu/carbone/modules/mods4car/', 'LINK', 13, 43),
(209, 'AccuWeather.com', 'http://www.accuweather.com/', 'LINK', 1, 49),
(250, 'The Weather Channel', 'http://www.weather.com/', 'LINK', 1, 45),
(252, 'Intellicast.com', 'http://www.intellicast.com/', 'LINK', 1, 46),
(253, 'Weather Underground', 'http://www.wunderground.com/', 'LINK', 1, 47),
(265, 'Nasa Clouds', 'http://asd-www-temp.larc.nasa.gov/SCOOL/cldchart.html', 'LINK', 5, 48),
(267, 'NASA', 'http://asd-www-temp.larc.nasa.gov/SCOOL/cldchart.html', 'LINK', 1, 44);
