package weather.common.data;

import java.io.Serializable;

/**
 * This class represents a property. Each <code>Property</code> has a propertyID
 * that uniquely identifies it.  This number is auto generated by MySQL Server
 * when a record of a property is created in the property table.  The propertyID
 * is the primary key of the courses table. IT also has propertyType which defines what kidn of 
 * property it is, propertyName represents the name of the property, propertyValue represents 
 * the value of the property
 * @author Xiang Li(2014)
 */
public class Property implements Serializable
{
        private static final long serialVersionUID = 1L;
        /**
        * The id of this property.
        * This number uniquely identifies instances of this class throughout the
        * program and in the database.  A value of -1 means that the number is not
        * yet specified.
        */   
        private int propertyID;
        
        //The type of the property
        private String propertyType;
        
        //The display name of the property type
        private String propertyTypeDisplayName;
        
        //The name of the property
        private String propertyName;
        
        //The display name of the property name
        private String propertyDisplayName;
        
        //The value of the property
        private String propertyValue;
        
        //If the property is editable
        private byte isEditable;
        
        //Descrition of the property
        private String notes;
        
        //The default value for the property
        private String defaultValue;
        
        //The value before last change
        private String previousValue;
        /**
        * The default constructor for the property class creates a new instance of 
        * property and sets its default values. The propertyNumber is set to -1 meaning
        * that this number is not yet specified.
        */
        public Property()
        {
            this.propertyID = -1;
            this.propertyName = null;
            this.propertyType = null;
            this.propertyTypeDisplayName = null;
            this.propertyDisplayName = null;
            this.propertyValue = null;
            this.isEditable = 1;
            this.notes = null;
            this.defaultValue = null;
            this.previousValue = null;
        }
        
        /**
         * The constructor of the Property class creates an instance of the Property
         * class and sets its values to those that are passed to it.
         * @param propertyID the ID of the property
         * @param propertyType the type of the property
         * @param propertyName the name of the property
         * @param propertyValue the value of the property
         */
        public Property(int propertyID, String propertyType, String propertyTypeDisplayName, String propertyName, 
                        String propertyDisplayName, String propertyValue, byte isEditable, String notes, 
                        String defaultValue, String previousValue)
        {
            this.propertyID = propertyID;
            this.propertyType = propertyType;
            this.propertyTypeDisplayName = propertyTypeDisplayName;
            this.propertyName = propertyName;
            this.propertyDisplayName = propertyDisplayName;
            this.propertyValue = propertyValue;
            this.isEditable = isEditable;
            this.notes = notes;
            this.defaultValue = defaultValue;
            this.previousValue = previousValue;
        }

    public byte getIsEditable() {
        return isEditable;
    }

    public void setIsEditable(byte isEditable) {
        this.isEditable = isEditable;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getDefaultValue() {
        return defaultValue;
    }

    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue;
    }

    public String getPreviousValue() {
        return previousValue;
    }

    public void setPreviousValue(String previousValue) {
        this.previousValue = previousValue;
    }

    public String getPropertyTypeDisplayName() {
        return propertyTypeDisplayName;
    }

    public void setPropertyTypeDisplayName(String propertyTypeDisplayName) {
        this.propertyTypeDisplayName = propertyTypeDisplayName;
    }

    public String getPropertyDisplayName() {
        return propertyDisplayName;
    }

    public void setPropertyDisplayName(String propertyDisplayName) {
        this.propertyDisplayName = propertyDisplayName;
    }

    /**
    * Return the id of the property
    * @return the property ID
    */
    public int getPropertyID() {
        return propertyID;
    }

    /**
     * Set the id of the property
     * @param propertyID 
     */
    public void setPropertyID(int propertyID) {
        this.propertyID = propertyID;
    }

    /**
     * Get the type of the property
     * @return the property type
     */
    public String getPropertyType() {
        return propertyType;
    }

    /**
     * Set the type of the property
     * @param propertyType 
     */
    public void setPropertyType(String propertyType) {
        this.propertyType = propertyType;
    }

    /**
     * Get the name of the property
     * @return the property name
     */
    public String getPropertyName() {
        return propertyName;
    }

    /**
     * Set the name of the property
     * @param propertyName 
     */
    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    /**
     * Get the value of the property
     * @return the property value
     */
    public String getPropertyValue() {
        return propertyValue;
    }

    /**
     * Set the value of the property
     * @param propertyValue 
     */
    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }
    
    /**
     * Returns the name of one property
     * @return the name of the property.
     */
    public String toString() 
    {
        return propertyType + " " + propertyName + " " + propertyValue;
    }
    
    /**
     * Returns the hash code of the property id
     * @return the hash code of the property id
     */
    public int hashCode()
    {
        return propertyID;
    }
        
    /**
     * Compare two properties
     * @param obj
     * @return true if equal, false otherwise
     */
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Property other = (Property) obj;
        if (this.propertyName != other.propertyName) {
            return false;
        }
        return true;
    }  
}
